"""add series metadata

Revision ID: a2d3e9d9027c
Revises: dbab7df34515
Create Date: 2026-08-25 18:30:32.820992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d3e9d9027c'
down_revision: Union[str, Sequence[str], None] = 'dbab7df34515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series_cast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=255), nullable=True),
    sa.Column('cast_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_cast_id'), 'series_cast', ['id'], unique=False)
    op.create_table('series_crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_crew_id'), 'series_crew', ['id'], unique=False)
    op.create_table('series_genres',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'genre_id')
    )
    op.create_table('series_keywords',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'keyword_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_keywords')
    op.drop_table('series_genres')
    op.drop_index(op.f('ix_series_crew_id'), table_name='series_crew')
    op.drop_table('series_crew')
    op.drop_index(op.f('ix_series_cast_id'), table_name='series_cast')
    op.drop_table('series_cast')
    # ### end Alembic commands ###
